{
  "ID": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
  "Root": {
    "alive": true,
    "content": [
      "98361746-4359-49a2-a63e-12b8f2af0093",
      "08255395-44cb-42c0-bdf7-84bcb8b99965",
      "143eff08-f6c5-461f-95ae-c5b7ddeb936a",
      "320a1f1d-9a39-455f-bb08-394d61dc5365",
      "40678d19-bd08-4237-9fdc-5af0af9e845f",
      "ef2265f5-1902-408f-9e16-89eb748a5d17",
      "d8c311db-8c44-45ea-914b-7d9047f34465",
      "eaaa72c6-026d-495d-ae36-4d9de09b203e",
      "dca1b758-1581-4cf7-81bb-24b4123035c3",
      "629cc2d3-888b-4b59-a0a0-e40669b10ec9",
      "abee43f6-2530-45fd-8777-6bf16d350b36",
      "259a7deb-7fb4-4822-9e66-e0831955e79c",
      "556f199f-32d9-4ddf-866e-b71d524e329a",
      "67ef27ac-7529-4d0a-aed1-02e87a4c6c50",
      "46c0c789-42cb-4750-9d8f-e704992c5d13",
      "caf7451e-26d6-48da-8f85-16dd70a95823",
      "d2899761-3f18-4f2d-888f-85b24df96703",
      "e2e30fcc-fda5-455e-ad2f-2bac7bd90a5e",
      "50353912-0ff0-4113-9480-d9ba55d6c715"
    ],
    "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
    "created_time": 1550389988184,
    "id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
    "ignore_block_count": true,
    "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
    "last_edited_time": 1550470680000,
    "parent_id": "324e4591-6ae9-4da8-bcc5-30139a2e19ac",
    "parent_table": "block",
    "properties": {
      "title": [
        [
          "Logging exceptions"
        ]
      ]
    },
    "type": "page",
    "version": 6,
    "content_resolved": [
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988177,
        "id": "98361746-4359-49a2-a63e-12b8f2af0093",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988177,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "If you want to log exceptions you can and should make use of the "
            ],
            [
              "logging.exception(msg)",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " method:"
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "If you want to log exceptions you can and should make use of the "
          },
          {
            "Text": "logging.exception(msg)",
            "AttrFlags": 2
          },
          {
            "Text": " method:"
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988180,
        "id": "08255395-44cb-42c0-bdf7-84bcb8b99965",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988180,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "language": [
            [
              "Plain Text"
            ]
          ],
          "title": [
            [
              "\u003e\u003e\u003e import logging\n\u003e\u003e\u003e logging.basicConfig()\n\u003e\u003e\u003e try:\n...     raise Exception('foo')\n... except:\n...     logging.exception('bar')\n...\nERROR:root:bar\nTraceback (most recent call last):\n  File \"\u003cstdin\u003e\", line 2, in \u003cmodule\u003e\nException: foo"
            ]
          ]
        },
        "type": "code",
        "version": 1,
        "code": "\u003e\u003e\u003e import logging\n\u003e\u003e\u003e logging.basicConfig()\n\u003e\u003e\u003e try:\n...     raise Exception('foo')\n... except:\n...     logging.exception('bar')\n...\nERROR:root:bar\nTraceback (most recent call last):\n  File \"\u003cstdin\u003e\", line 2, in \u003cmodule\u003e\nException: foo",
        "code_language": "Plain Text"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988180,
        "id": "143eff08-f6c5-461f-95ae-c5b7ddeb936a",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988180,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "Do not pass the exception as argument:",
              [
                [
                  "b"
                ]
              ]
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "Do not pass the exception as argument:",
            "AttrFlags": 1
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988181,
        "id": "320a1f1d-9a39-455f-bb08-394d61dc5365",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988181,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "As "
            ],
            [
              "logging.exception(msg)",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " expects a "
            ],
            [
              "msg",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " arg, it is a common pitfall to pass the exception into the logging call like this:"
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "As "
          },
          {
            "Text": "logging.exception(msg)",
            "AttrFlags": 2
          },
          {
            "Text": " expects a "
          },
          {
            "Text": "msg",
            "AttrFlags": 2
          },
          {
            "Text": " arg, it is a common pitfall to pass the exception into the logging call like this:"
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988181,
        "id": "40678d19-bd08-4237-9fdc-5af0af9e845f",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988181,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "language": [
            [
              "Plain Text"
            ]
          ],
          "title": [
            [
              "\u003e\u003e\u003e try:\n...     raise Exception('foo')\n... except Exception as e:\n...     logging.exception(e)\n...\nERROR:root:foo\nTraceback (most recent call last):\n  File \"\u003cstdin\u003e\", line 2, in \u003cmodule\u003e\nException: foo"
            ]
          ]
        },
        "type": "code",
        "version": 1,
        "code": "\u003e\u003e\u003e try:\n...     raise Exception('foo')\n... except Exception as e:\n...     logging.exception(e)\n...\nERROR:root:foo\nTraceback (most recent call last):\n  File \"\u003cstdin\u003e\", line 2, in \u003cmodule\u003e\nException: foo",
        "code_language": "Plain Text"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988181,
        "id": "ef2265f5-1902-408f-9e16-89eb748a5d17",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988181,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "While it might look as if this is the right thing to do at first, it is actually problematic due to the reason how exceptions and various encoding work together in the logging module:"
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "While it might look as if this is the right thing to do at first, it is actually problematic due to the reason how exceptions and various encoding work together in the logging module:"
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988181,
        "id": "d8c311db-8c44-45ea-914b-7d9047f34465",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988181,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "language": [
            [
              "Plain Text"
            ]
          ],
          "title": [
            [
              "\u003e\u003e\u003e try:\n...     raise Exception(u'föö')\n... except Exception as e:\n...     logging.exception(e)\n...\nTraceback (most recent call last):\n  File \"/.../python2.7/logging/__init__.py\", line 861, in emit\n    msg = self.format(record)\n  File \"/.../python2.7/logging/__init__.py\", line 734, in format\n    return fmt.format(record)\n  File \"/.../python2.7/logging/__init__.py\", line 469, in format\n    s = self._fmt % record.__dict__\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)\nLogged from file \u003cstdin\u003e, line 4"
            ]
          ]
        },
        "type": "code",
        "version": 1,
        "code": "\u003e\u003e\u003e try:\n...     raise Exception(u'föö')\n... except Exception as e:\n...     logging.exception(e)\n...\nTraceback (most recent call last):\n  File \"/.../python2.7/logging/__init__.py\", line 861, in emit\n    msg = self.format(record)\n  File \"/.../python2.7/logging/__init__.py\", line 734, in format\n    return fmt.format(record)\n  File \"/.../python2.7/logging/__init__.py\", line 469, in format\n    s = self._fmt % record.__dict__\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)\nLogged from file \u003cstdin\u003e, line 4",
        "code_language": "Plain Text"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988183,
        "id": "eaaa72c6-026d-495d-ae36-4d9de09b203e",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988183,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "Trying to log an exception that contains unicode chars, this way will "
            ],
            [
              "fail miserably",
              [
                [
                  "a",
                  "http://stackoverflow.com/questions/31137568/properly-logging-unicode-utf-8-exceptions-in-python-2"
                ]
              ]
            ],
            [
              ". It will hide the stacktrace of the original exception by overriding it with a new one that is raised during formatting of your "
            ],
            [
              "logging.exception(e)",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " call."
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "Trying to log an exception that contains unicode chars, this way will "
          },
          {
            "Text": "fail miserably",
            "Link": "http://stackoverflow.com/questions/31137568/properly-logging-unicode-utf-8-exceptions-in-python-2"
          },
          {
            "Text": ". It will hide the stacktrace of the original exception by overriding it with a new one that is raised during formatting of your "
          },
          {
            "Text": "logging.exception(e)",
            "AttrFlags": 2
          },
          {
            "Text": " call."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988183,
        "id": "dca1b758-1581-4cf7-81bb-24b4123035c3",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988183,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "Obviously, in your own code, you might be aware of the encoding in exceptions. However, 3rd party libs might handle this in a different way."
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "Obviously, in your own code, you might be aware of the encoding in exceptions. However, 3rd party libs might handle this in a different way."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988183,
        "id": "629cc2d3-888b-4b59-a0a0-e40669b10ec9",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988183,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "Correct Usage:",
              [
                [
                  "b"
                ]
              ]
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "Correct Usage:",
            "AttrFlags": 1
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988183,
        "id": "abee43f6-2530-45fd-8777-6bf16d350b36",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988183,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "If instead of the exception you just pass a message and let python do its magic, it will work:"
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "If instead of the exception you just pass a message and let python do its magic, it will work:"
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988183,
        "id": "259a7deb-7fb4-4822-9e66-e0831955e79c",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988183,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "language": [
            [
              "Plain Text"
            ]
          ],
          "title": [
            [
              "\u003e\u003e\u003e try:\n...     raise Exception(u'föö')\n... except Exception as e:\n...     logging.exception('bar')\n...\nERROR:root:bar\nTraceback (most recent call last):\n  File \"\u003cstdin\u003e\", line 2, in \u003cmodule\u003e\nException: f\\xf6\\xf6"
            ]
          ]
        },
        "type": "code",
        "version": 1,
        "code": "\u003e\u003e\u003e try:\n...     raise Exception(u'föö')\n... except Exception as e:\n...     logging.exception('bar')\n...\nERROR:root:bar\nTraceback (most recent call last):\n  File \"\u003cstdin\u003e\", line 2, in \u003cmodule\u003e\nException: f\\xf6\\xf6",
        "code_language": "Plain Text"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988183,
        "id": "556f199f-32d9-4ddf-866e-b71d524e329a",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988183,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "As you can see we don’t actually use "
            ],
            [
              "e",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " in that case, the call to "
            ],
            [
              "logging.exception(...)",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " magically formats the most recent exception."
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "As you can see we don’t actually use "
          },
          {
            "Text": "e",
            "AttrFlags": 2
          },
          {
            "Text": " in that case, the call to "
          },
          {
            "Text": "logging.exception(...)",
            "AttrFlags": 2
          },
          {
            "Text": " magically formats the most recent exception."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988183,
        "id": "67ef27ac-7529-4d0a-aed1-02e87a4c6c50",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988183,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "Logging exceptions with non ERROR log levels",
              [
                [
                  "b"
                ]
              ]
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "Logging exceptions with non ERROR log levels",
            "AttrFlags": 1
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988183,
        "id": "46c0c789-42cb-4750-9d8f-e704992c5d13",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988183,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "If you want to log an exception with another log level than ERROR, you can use the the "
            ],
            [
              "exc_info",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " argument of the default loggers:"
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "If you want to log an exception with another log level than ERROR, you can use the the "
          },
          {
            "Text": "exc_info",
            "AttrFlags": 2
          },
          {
            "Text": " argument of the default loggers:"
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988184,
        "id": "caf7451e-26d6-48da-8f85-16dd70a95823",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988184,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "language": [
            [
              "Plain Text"
            ]
          ],
          "title": [
            [
              "logging.debug('exception occurred', exc_info=1)\nlogging.info('exception occurred', exc_info=1)\nlogging.warning('exception occurred', exc_info=1)"
            ]
          ]
        },
        "type": "code",
        "version": 1,
        "code": "logging.debug('exception occurred', exc_info=1)\nlogging.info('exception occurred', exc_info=1)\nlogging.warning('exception occurred', exc_info=1)",
        "code_language": "Plain Text"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988184,
        "id": "d2899761-3f18-4f2d-888f-85b24df96703",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988184,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "Accessing the exception’s message",
              [
                [
                  "b"
                ]
              ]
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "Accessing the exception’s message",
            "AttrFlags": 1
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988184,
        "id": "e2e30fcc-fda5-455e-ad2f-2bac7bd90a5e",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988184,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "Be aware that libraries out there might throw exceptions with messages as any of unicode or (utf-8 if you’re lucky) byte-strings. If you really need to access an exception’s text, the only reliable way, that will always work, is to use "
            ],
            [
              "repr(e)",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " or the "
            ],
            [
              "%r",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " string formatting:"
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "Be aware that libraries out there might throw exceptions with messages as any of unicode or (utf-8 if you’re lucky) byte-strings. If you really need to access an exception’s text, the only reliable way, that will always work, is to use "
          },
          {
            "Text": "repr(e)",
            "AttrFlags": 2
          },
          {
            "Text": " or the "
          },
          {
            "Text": "%r",
            "AttrFlags": 2
          },
          {
            "Text": " string formatting:"
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550389988184,
        "id": "50353912-0ff0-4113-9480-d9ba55d6c715",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550389988184,
        "parent_id": "3e437060-fa88-4fae-a842-7805bcd0dbfe",
        "parent_table": "block",
        "properties": {
          "language": [
            [
              "Plain Text"
            ]
          ],
          "title": [
            [
              "\u003e\u003e\u003e try:\n...     raise Exception(u'föö')\n... except Exception as e:\n...     logging.exception('received this exception: %r' % e)\n...\nERROR:root:received this exception: Exception(u'f\\xf6\\xf6',)\nTraceback (most recent call last):\n  File \"\u003cstdin\u003e\", line 2, in \u003cmodule\u003e\nException: f\\xf6\\xf6"
            ]
          ]
        },
        "type": "code",
        "version": 1,
        "code": "\u003e\u003e\u003e try:\n...     raise Exception(u'föö')\n... except Exception as e:\n...     logging.exception('received this exception: %r' % e)\n...\nERROR:root:received this exception: Exception(u'f\\xf6\\xf6',)\nTraceback (most recent call last):\n  File \"\u003cstdin\u003e\", line 2, in \u003cmodule\u003e\nException: f\\xf6\\xf6",
        "code_language": "Plain Text"
      }
    ],
    "title": "Logging exceptions"
  },
  "Users": [
    {
      "email": "kkowalczyk@gmail.com",
      "family_name": "Kowalczyk",
      "given_name": "Krzysztof",
      "id": "bb760e2d-d679-4b64-b2a9-03005b21870a",
      "locale": "en",
      "mobile_onboarding_completed": true,
      "onboarding_completed": true,
      "profile_photo": "https://s3-us-west-2.amazonaws.com/public.notion-static.com/2dcaa66c-7674-4ff6-9924-601785b63561/head-bw-640x960.png",
      "time_zone": "America/Los_Angeles",
      "version": 18
    }
  ],
  "Tables": null
}