{
  "ID": "ff7b7dd9-772c-47e7-8a79-7eec5906c52e",
  "Root": {
    "id": "ff7b7dd9-772c-47e7-8a79-7eec5906c52e",
    "alive": true,
    "content": [
      "214840ee-d9bf-4908-bd80-7e126b6afba7",
      "625553a5-99e3-42b7-b730-eb2066d4e70f",
      "879e0790-cebe-47cd-88d9-580e984e963e",
      "3270f2e0-7b98-44c4-8d08-ac83e6403db1",
      "5d94ebad-3b73-4627-a923-3af2d5a89eec"
    ],
    "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
    "created_time": 1549524861222,
    "format": {
      "page_full_width": true,
      "page_small_text": true
    },
    "ignore_block_count": true,
    "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
    "last_edited_time": 1549939200000,
    "parent_id": "307cbc92-1d45-43c5-9927-7963d630a818",
    "parent_table": "block",
    "properties": {
      "title": [
        [
          "Await in catch and finally"
        ]
      ]
    },
    "type": "page",
    "version": 14,
    "content_resolved": [
      {
        "id": "214840ee-d9bf-4908-bd80-7e126b6afba7",
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1549524861220,
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1549524861220,
        "parent_id": "ff7b7dd9-772c-47e7-8a79-7eec5906c52e",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "It is possible to use "
            ],
            [
              "await",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " expression to apply "
            ],
            [
              "await operator",
              [
                [
                  "a",
                  "https://msdn.microsoft.com/en-us/library/hh156528.aspx"
                ]
              ]
            ],
            [
              " to "
            ],
            [
              "Tasks",
              [
                [
                  "a",
                  "https://msdn.microsoft.com/en-us/library/system.threading.tasks.task.aspx"
                ]
              ]
            ],
            [
              " or "
            ],
            [
              "Task(Of TResult)",
              [
                [
                  "a",
                  "https://msdn.microsoft.com/en-us/library/dd321424.aspx"
                ]
              ]
            ],
            [
              " in the "
            ],
            [
              "catch",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " and "
            ],
            [
              "finally",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " blocks in C#6."
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "It is possible to use "
          },
          {
            "Text": "await",
            "AttrFlags": 2
          },
          {
            "Text": " expression to apply "
          },
          {
            "Text": "await operator",
            "Link": "https://msdn.microsoft.com/en-us/library/hh156528.aspx"
          },
          {
            "Text": " to "
          },
          {
            "Text": "Tasks",
            "Link": "https://msdn.microsoft.com/en-us/library/system.threading.tasks.task.aspx"
          },
          {
            "Text": " or "
          },
          {
            "Text": "Task(Of TResult)",
            "Link": "https://msdn.microsoft.com/en-us/library/dd321424.aspx"
          },
          {
            "Text": " in the "
          },
          {
            "Text": "catch",
            "AttrFlags": 2
          },
          {
            "Text": " and "
          },
          {
            "Text": "finally",
            "AttrFlags": 2
          },
          {
            "Text": " blocks in C#6."
          }
        ]
      },
      {
        "id": "625553a5-99e3-42b7-b730-eb2066d4e70f",
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1549524861221,
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1549524861221,
        "parent_id": "ff7b7dd9-772c-47e7-8a79-7eec5906c52e",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "It was not possible to use the "
            ],
            [
              "await",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " expression in the "
            ],
            [
              "catch",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " and "
            ],
            [
              "finally",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " blocks in earlier versions due to compiler limitations. C#6 makes awaiting async tasks a lot easier by allowing the "
            ],
            [
              "await",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " expression."
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "It was not possible to use the "
          },
          {
            "Text": "await",
            "AttrFlags": 2
          },
          {
            "Text": " expression in the "
          },
          {
            "Text": "catch",
            "AttrFlags": 2
          },
          {
            "Text": " and "
          },
          {
            "Text": "finally",
            "AttrFlags": 2
          },
          {
            "Text": " blocks in earlier versions due to compiler limitations. C#6 makes awaiting async tasks a lot easier by allowing the "
          },
          {
            "Text": "await",
            "AttrFlags": 2
          },
          {
            "Text": " expression."
          }
        ]
      },
      {
        "id": "879e0790-cebe-47cd-88d9-580e984e963e",
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1549524861221,
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1549939140000,
        "parent_id": "ff7b7dd9-772c-47e7-8a79-7eec5906c52e",
        "parent_table": "block",
        "properties": {
          "language": [
            [
              "C#"
            ]
          ],
          "title": [
            [
              "try\n{\n    //since C#5\n    await service.InitializeAsync();\n} \ncatch (Exception e)\n{\n    //since C#6\n    await logger.LogAsync(e);\n}\nfinally\n{\n    //since C#6\n    await service.CloseAsync();\n}"
            ]
          ]
        },
        "type": "code",
        "version": 3,
        "code": "try\n{\n    //since C#5\n    await service.InitializeAsync();\n} \ncatch (Exception e)\n{\n    //since C#6\n    await logger.LogAsync(e);\n}\nfinally\n{\n    //since C#6\n    await service.CloseAsync();\n}",
        "code_language": "C#"
      },
      {
        "id": "3270f2e0-7b98-44c4-8d08-ac83e6403db1",
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1549524861222,
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1549524861222,
        "parent_id": "ff7b7dd9-772c-47e7-8a79-7eec5906c52e",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "It was required in C# 5 to use a "
            ],
            [
              "bool",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " or declare an "
            ],
            [
              "Exception",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " outside the try catch to perform async operations. This method is shown in the following example:"
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "It was required in C# 5 to use a "
          },
          {
            "Text": "bool",
            "AttrFlags": 2
          },
          {
            "Text": " or declare an "
          },
          {
            "Text": "Exception",
            "AttrFlags": 2
          },
          {
            "Text": " outside the try catch to perform async operations. This method is shown in the following example:"
          }
        ]
      },
      {
        "id": "5d94ebad-3b73-4627-a923-3af2d5a89eec",
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1549524861222,
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1549939200000,
        "parent_id": "ff7b7dd9-772c-47e7-8a79-7eec5906c52e",
        "parent_table": "block",
        "properties": {
          "language": [
            [
              "C#"
            ]
          ],
          "title": [
            [
              "bool error = false;\nException ex = null;\n\ntry\n{\n    // Since C#5\n    await service.InitializeAsync();\n} \ncatch (Exception e)\n{\n    // Declare bool or place exception inside variable\n    error = true;\n    ex = e;\n}\n\n// If you don't use the exception\nif (error)\n{\n    // Handle async task\n}\n\n// If want to use information from the exception\nif (ex != null)\n{\n    await logger.LogAsync(e);\n}    \n\n// Close the service, since this isn't possible in the finally\nawait service.CloseAsync();"
            ]
          ]
        },
        "type": "code",
        "version": 10,
        "code": "bool error = false;\nException ex = null;\n\ntry\n{\n    // Since C#5\n    await service.InitializeAsync();\n} \ncatch (Exception e)\n{\n    // Declare bool or place exception inside variable\n    error = true;\n    ex = e;\n}\n\n// If you don't use the exception\nif (error)\n{\n    // Handle async task\n}\n\n// If want to use information from the exception\nif (ex != null)\n{\n    await logger.LogAsync(e);\n}    \n\n// Close the service, since this isn't possible in the finally\nawait service.CloseAsync();",
        "code_language": "C#"
      }
    ],
    "title": "Await in catch and finally",
    "format_page": {
      "page_cover": "",
      "page_cover_position": 0,
      "page_font": "",
      "page_full_width": true,
      "page_icon": "",
      "page_small_text": true
    }
  },
  "Users": [
    {
      "email": "kkowalczyk@gmail.com",
      "family_name": "Kowalczyk",
      "given_name": "Krzysztof",
      "id": "bb760e2d-d679-4b64-b2a9-03005b21870a",
      "locale": "",
      "mobile_onboarding_completed": true,
      "onboarding_completed": true,
      "profile_photo": "https://s3-us-west-2.amazonaws.com/public.notion-static.com/2dcaa66c-7674-4ff6-9924-601785b63561/head-bw-640x960.png",
      "time_zone": "",
      "version": 94
    }
  ],
  "Tables": null
}